### PR TITLE
Add sample closure question

### PR DESCRIPTION
**Pull request by JustinMcNamara74**
Added an example interview question that could test an interviewee's understand of JavaScript closures.

In order to keep the `README` clean, I made a separate file for `closure`-related questions.

### CODE REVIEW

**Comment by ufocoder** [comment]
@JustinMcNamara74 You've pulled the pretty good idea of using closure in currying, but if you mark you as closure-question your question should be placed in the existing [closure section](https://github.com/ufocoder/javascript.interview#closure-in-javascript)

Please add a question `Does any currying function have a closure?` and write an answer and explanation with several sentences then. It'll be a pretty good question. 

Thanks a lot ;)

**Comment by JustinMcNamara74** [comment]
@ufocoder I addressed your comments. Let me know if there are any other issues.

**Comment by ufocoder** [comment]
@JustinMcNamara74 Change question part for `Does any currying function have a closure? Give an example, please`. And I merge your pull request. Answer part is cool ;)

You can add the question about functional programming concept In the next pull request of course if you want

**Comment by JustinMcNamara74** [comment]
> @JustinMcNamara74 Change question part for `Does any currying function have a closure? Give an example, please`. And I merge your pull request. Answer part is cool ;)
> 
> You can add the question about functional programming concept In the next pull request of course if you want

@ufocoder done

**Pull request merged**
